sudo: required
services:
    - docker

language: go

go:
    - "1.10.x"
    - "1.11.x"

before_install:
    - set -e
    
install:
    - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

before_script: 
    - dep ensure -v

script:
  - go clean github.com/uknth/faker/...
  - go test github.com/uknth/faker/...

  - docker build -t faker:latest . 
  - docker run -p12000:12000 -d faker:latest
  - docker ps -a

  - curl -v "http://127.0.0.1:12000/ping?q=*&fields=uniqueId"

after_success:
  - ./scripts/push-to-dockerhub.sh

notifications:
  email:
    - uknth@outlook.com
