name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Clean
        run: go clean github.com/uknth/faker/...

      - name: Tests
        run: go test github.com/uknth/faker/...

      - name: Go Build
        run: |
          env GOOS=linux GOARCH=amd64 go build -o bin/faker github.com/uknth/faker/cmd/faker

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.8.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: |
            ghcr.io/uknth/faker
          tag-sha: true

      - name: Push to GitHub Packages
        if: github.event.ref_type != 'tag' && github.event_name != 'release'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
