name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Clean
      run: go clean github.com/uknth/faker/...
      
    - name: Tests
      run: go test github.com/uknth/faker/...
      
    - name: Build
      run: go build -v github.com/uknth/faker/...
    
    - name: Docker Build
      run: docker build -t faker:latest .
